\connect postgres

CREATE SCHEMA IF NOT EXISTS auth_db AUTHORIZATION eduadmin;
CREATE SCHEMA IF NOT EXISTS user_db AUTHORIZATION eduadmin;
CREATE SCHEMA IF NOT EXISTS club_db AUTHORIZATION eduadmin;
CREATE SCHEMA IF NOT EXISTS course_db AUTHORIZATION eduadmin;
CREATE SCHEMA IF NOT EXISTS assignment_db AUTHORIZATION eduadmin;
CREATE SCHEMA IF NOT EXISTS event_db AUTHORIZATION eduadmin;
CREATE SCHEMA IF NOT EXISTS post_db AUTHORIZATION eduadmin;
CREATE SCHEMA IF NOT EXISTS gamification_db AUTHORIZATION eduadmin;
