package com.educonnect.clubservice.model;

public enum ApprovalType {
    ROLE_CHANGE,
    RESIGNATION,
    ADVISOR_CHANGE,
    CLUB_CLOSURE,
    MEMBER_EXPULSION,
    CLUB_PROFILE_UPDATE,
    CLUB_LOGO_CHANGE,
    CLUB_ANNOUNCEMENT,
    CLUB_BUDGET,
    CLUB_FINANCE_ENTRY,
    CLUB_SPONSORSHIP,
    CLUB_MEETING_MINUTES
}
