package com.educonnect.clubservice.model;

public enum DecisionAction {
    SUBMITTED,
    PRESIDENT_APPROVED,
    APPROVED,
    REJECTED,
    WITHDRAWN,
    PRESIDENT_REMOVED,
    PRESIDENT_APPOINTED,
    VICE_PRESIDENT_PROMOTED,
    PRESIDENCY_VACANT,
    ADVISOR_RESIGNED,
    ADVISOR_LEFT,
    CLUB_FOUNDED,
    CLUB_CLOSED,
    MEMBERSHIP_REVIEWED,
    MEMBERSHIP_APPROVED,
    MEMBERSHIP_REJECTED
}
