package com.educonnect.clubservice.security;

public enum ClubPermission {
    VIEW_MEMBERS,
    VIEW_MANAGEMENT_DATA,
    VIEW_DECISIONS,
    MANAGE_MEMBERSHIP_REQUESTS,
    REVIEW_MEMBERSHIP_REQUESTS,
    PROPOSE_POSITION_CHANGE,
    UPDATE_CLUB_PROFILE,
    PREPARE_PROFILE_CHANGE,
    PREPARE_LOGO_CHANGE,
    PREPARE_ANNOUNCEMENT,
    PREPARE_FINANCE,
    PREPARE_SPONSORSHIP,
    VIEW_FINANCE,
    PREPARE_MINUTES,
    PREPARE_ACTIVITY_REPORT,
    PREPARE_AUDIT_REPORT,
    PREPARE_ELECTION,
    PROPOSE_ADVISOR_CHANGE,
    APPROVE_AS_PRESIDENT,
    REQUEST_CLUB_CLOSURE,
    CREATE_EVENT,
    PREPARE_EVENT,
    MANAGE_EVENT_OPERATIONS,
    ADVISE
}
