package com.educonnect.clubservice.security;

public enum ClubPermission {
    VIEW_MEMBERS,
    VIEW_MANAGEMENT_DATA,
    MANAGE_MEMBERSHIP_REQUESTS,
    PROPOSE_POSITION_CHANGE,
    UPDATE_CLUB_PROFILE,
    PROPOSE_ADVISOR_CHANGE,
    APPROVE_AS_PRESIDENT,
    REQUEST_CLUB_CLOSURE,
    CREATE_EVENT,
    MANAGE_EVENT_OPERATIONS,
    ADVISE
}
