spring:
  application:
    name: event-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true
      username: ${CONFIG_SERVER_USER:educonnect}
      password: ${CONFIG_SERVER_PASSWORD}
